# Generated by Django 3.1.2 on 2020-10-12 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20201012_0948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='verification_token',
        ),
    ]
